# Logo
logo_image_source: 

# Index Page
index_banner_text: Citrus
index_banner_text_secondary: 博观而约取
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  #Contact: /contact

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: /blog/img/avatar_1.jpg
about_widget_text: "My name is Citrus Zhou"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: hicitrus-com

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: http://hicitrus.com
    fa_icon: fa-home
  - url: http://weibo.com/zhouyou421
    fa_icon: fa-weibo
  #- url: https://twitter.com/Citrus__
    #fa_icon: fa-twitter
  #- url: https://dribbble.com/
    #fa_icon: fa-dribbble 
  - url: https://github.com/citrusu
    fa_icon: fa-github
  #- url: https://plus.google.com/
    #fa_icon: fa-google-plus
  #- url: https://www.behance.net/
    #fa_icon: fa-behance
  #- url: https://500px.com/
    #fa_icon: fa-500px
  - url: mailto:citruszhou@gmail.com
    fa_icon: fa-envelope-o
  #- url: /#
    #fa_icon: fa-rss

# Footer about
footer_about: "@Untitled. All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
